
prod_svy_estimation_schema <-
  data.frame(
    survey_id = character(0),
    cache_id = character(0),
    region_code = character(0),
    wb_region_code = character(0),
    country_code = character(0),
    reporting_year = numeric(0),
    surveyid_year = numeric(0),
    survey_year = numeric(0),
    survey_time = character(0),
    survey_acronym = character(0),
    survey_coverage = character(0),
    survey_comparability = numeric(0),
    comparable_spell = character(0),
    welfare_type = character(0),
    reporting_level = character(0),
    survey_mean_lcu = numeric(0),
    survey_mean_ppp = numeric(0),
    survey_median_ppp = numeric(0),
    survey_median_lcu = numeric(0),
    predicted_mean_ppp = numeric(0),
    ppp = numeric(0),
    cpi = numeric(0),
    reporting_pop = numeric(0),
    reporting_gdp = numeric(0),
    reporting_pce = numeric(0),
    pop_data_level = character(0),
    gdp_data_level = character(0),
    pce_data_level = character(0),
    cpi_data_level = character(0),
    ppp_data_level = character(0),
    distribution_type = character(0),
    gd_type = character(0),
    is_interpolated = logical(0),
    is_used_for_line_up = logical(0),
    is_used_for_aggregation = logical(0),
    estimation_type = character(0),
    display_cp = numeric(0)
  )
